HERMES_ORCISH = {
	LanguageID = 1,
	ALPHABET =  {
		{ "AAZ", "AA5" },
		{ "DAL", "🜁🜁🜇" },
		{ "GES", "A🜃🜅" },
		{ "GEZ", "AB🜆" },
		{ "GOL", "ADズ" },
		{ "GOT", "AA🜄" },
		{ "GUL", "AC6" },
		{ "KAZ", "AB1" },
		{ "KEK", "AD6" },
		{ "KIL", "AB6" },
		{ "KOG", "Aザ🜇" },
		{ "LOK", "AA0" },
		{ "MAG", "AAゼ" },
		{ "MAK", "AD🜄" },
		{ "MAZ", "ザシ🜃" },
		{ "MOG", "AA🜇" },
		{ "MOT", "Aジ🜁" },
		{ "NAK", "AD🜆" },
		{ "NO'", "AAザ" },
		{ "NOG", "AAス" },
		{ "NUK", "AB7" },
		{ "OGE", "AC🜂" },
		{ "OGG", "AB0" },
		{ "OSH", "Aザ🜂" },
		{ "RAG", "Aザ🜁" },
		{ "RAT", "Aザス" },
		{ "RAZ", "AB🜇" },
		{ "RE'", "AAズ" },
		{ "REG", "ACセ" },
		{ "REV", "AA🜅" },
		{ "RO'", "A0セ" },
		{ "RUK", "AC4" },
		{ "TAR", "AA1" },
		{ "THR", "AAセ" },
		{ "THU", "AA🜆" },
		{ "TOV", "Aシセ" },
		{ "UL'", "🜁🜁🜄" },
		{ "ZIL", "Aザシ" },
		{ "ZUG", "AB5" },
		{ "KA", "🜅A" },
		{ "GI", "7A" },
		{ "IL", "4A" },
		{ "HA", "5A" },
		{ "KO", "6A" },
		{ "MU", "8A" },
		{ "MA", "🜄A" },
		{ "NO", "🜁A" },
		{ "TH", "🜃A" },
		{ "OG", "ゾA" },
		{ "ZA", "トA" },
		{ "DO", "ヂA" },
		{ "GR", "ッA" },
		{ "TA", "ドA" },
		{ "RO", "🜂A" },
		{ "RE", "🜔A" },
		{ "GO", "🜈A" },
		{ "ZU", "🜉A" },
		{ "UR", "ザB" },
		{ "GE", "ッB" },
		{ "MO", "タザ" },
		{ "AA", "ダザ" },
		{ "NA", "デザ" },
		{ "ZI", "🜍ザ" },
		{ "GU", "🜑ザ" },
		{ "RA", "🜒ザ" },
		{ "LO", "🜔ザ" },
		{ "TO", "🜊ザ" },
		{ "KI", "🜏ザ" },
		{ "OS", "🜓🜁" },
		{ 'AG', 'E5' },
		{ 'A', '1' },
		{ 'D', '𒈞' },
		{ 'G', 'Ü' },
		{ 'H', 'Ų' },
		{ 'I', 'Ȉ' },
		{ 'K', 'Ƥ' },
		{ 'L', '3' },
		{ 'M', 'Ď' },
		{ 'N', 'ϼ' },
		{ 'O', 'ࣞ' },
		{ 'R', 'ర' },
		{ 'T', 'ू' },
		{ 'U', 'Dz' }, -- `Il` Looks like two sticks
		{ 'Z', 'দ' }
	},
    
	SUBSTITUTES = {
		B = 'H',
		C = 'K',
		E = 'I',
		F = 'TH',
		J = 'G',
		P = 'H',
		Q = 'K',
		S = 'Z',
		X = 'KZ',
		V = 'TH',
		W = 'TH',
		Y = 'I',
	},

	SEPARATOR = { 
		INPUT = 'x',
		OUTPUT = 'n'
	}
}